image: node:latest

stages:
  - install
  - verify

install_deps:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules

unit_tests:
  stage: verify
  needs:
    - install_deps
  script:
    - npm run test

eslint:
  stage: verify
  needs:
    - install_deps
  script:
    - npm run eslint

e2e:
  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  stage: verify
  needs:
    - install_deps
  script:
    - npm ci
    - npm run start &
    - npm run cypress:ci
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day  

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - /root/.cache/Cypress
    - .npm/